# Generated by Django 5.1.7 on 2025-04-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_storedfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedfile",
            name="public_link",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
